version: "3,9"
services:
  web:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
    - .:/usr/share/nginx/html
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80t

